version: '3.8'
services:
  db:
    image: postgres:15
    container_name: smartmatch-db
    environment:
      - POSTGRES_DB=smartmatch_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"