version: '3.8'
services:
  db:
    image: postgres:15
    container_name: smartmatch-db
    environment:
      - POSTGRES_DB=smartmatch_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartmatch-rabbitmq
    ports:
      - "5672:5672"   # Порт для AMQP (приложения)
      - "15672:15672" # Порт для Management UI (браузер)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest