server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: match-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/matches/**

        - id: streaming-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/streams/**

        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/notifications/**