server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/auth/**

        - id: match-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/matches/**
          filters:
            - AuthenticationFilter

        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter
        - id: streaming-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/streams/**
          filters:
            - AuthenticationFilter

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG

jwt:
  secret: your_very_secret_key_here
  expiration: 86400000